spring:
    application:
      name: springsecurity
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cqrs
      username: spcamp
      password: spcamp
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format-sql: true
jwt:
  secret: nlga6fg6PfWZMIU9Vow9QYwuCSyLYsxhXQ4wSfx+q+S9b6OxM53SReYoGpHpxKZakmmNHo9EnCVZgumo+K+C5Q==
  expiration: 1800000 #30분(access token)
  refresh-expiration: 604800000 #7일(refresh token)