### 1. 응답 설계 - 회원 목록 조회
GET http://localhost:8080/api/v1/response/users


### 2. 응답 설계 - query string 검색
GET http://localhost:8080/api/v1/response/users?status=active&name=판다

### 3. 응답 설계 - 회원 단건 조회
GET http://localhost:8080/api/v1/response/users/1

### 4. 응답 설계 - 201 Created + Location header
POST http://localhost:8080/api/v1/response/users
Content-Type: application/json

{
  "id": "user04",
  "qwd": "pass04",
  "name": "호랑이",
  "status": "inactive"
}

### 5. 응답 설계 - PUT 204 No Content
PUT http://localhost:8080/api/v1/response/users/1
Content-Type: application/json

{
  "id": "user011",
  "qwd": "pass011",
  "name": "코알라"
}

### 6. 응답 설계 - 204 No Content 회원 삭제
DELETE http://localhost:8080/api/v1/response/users/3

### section02
### 7. Bean Validation - 정상 등록
POST http://localhost:8080/api/v1/validation/users
Content-Type: application/json

{
  "id": "user01",
  "pwd": "pass01",
  "name": "곰",
  "enrollDate": "2026-05-01T00:00:00.000+00:00"
}

### 8. Bean Validation - 필수 값 누락 400
POST http://localhost:8080/api/v1/validation/users
Content-Type: application/json

{
  "id": "user01",
  "pwd": "pass01",
  "name": "곰곰곰곰곰곰곰곰곰곰곰곰곰곰곰",
  "enrollDate": "2026-05-01T00:00:00.000+00:00"
}

### 9. 전역 예외 응답 - 존재하지 않는 회원으로 404
GET http://localhost:8080/api/v1/validation/users/999